apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bonita-test
    app.kubernetes.io/name: bonita
  name: bonita-test
spec:
  ports:
  - name: hazelcast
    port: 5701
    protocol: TCP
    targetPort: 5701
  - name: bonita
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: bonita-test
    app.kubernetes.io/name: bonita
  sessionAffinity: None
  type: LoadBalancer