apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonita-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: bonita-test
      app.kubernetes.io/name: bonita
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bonita-test
        app.kubernetes.io/name: bonita
    spec:
      serviceAccountName: bonitaserviceaccount
      hostname: bonita
      containers:
      - envFrom:
        - secretRef:
            name: bonita-test-creds
        - configMapRef:
            name: bonita-test
        image: bonitasoft.jfrog.io/docker/bonita-subscription:10.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            httpHeaders:
            - name: Authorization
              value: Basic bW9uaXRvcmluZzpteU1vbml0b3JpbmdTZWNyZXQ=
            - name: User-Agent
              value: BonitaHealthCheck/1.0
            path: /bonita/healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        name: bonita
        ports:
        - containerPort: 5701
          name: hazelcast
          protocol: TCP
        - containerPort: 8080
          name: bonita
          protocol: TCP
        resources:
          limits:
            cpu: 2
            memory: 2000Mi
          requests:
            cpu: 2
            memory: 2000Mi
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
        startupProbe:
          failureThreshold: 20
          httpGet:
            httpHeaders:
            - name: Authorization
              value: Basic bW9uaXRvcmluZzpteU1vbml0b3JpbmdTZWNyZXQ=
            - name: User-Agent
              value: BonitaHealthCheck/1.0
            path: /bonita/healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - name: bonita-scripts
          mountPath: /opt/custom-init.d
        - name: bonita-lic
          mountPath: /opt/bonita_lic
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: imagepullsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: bonita-scripts
        configMap:
          name: bonita-scripts
          items:
              - key: bonita_setup.sh
                path: bonita_setup.sh
              - key: log4j2-appenders.xml
                path: log4j2-appenders.xml
              - key: bonita-platform-sp-cluster-custom.properties
                path: bonita-platform-sp-cluster-custom.properties
      - name: bonita-lic
        configMap:
          name: bonita-license
          items:
            - key: bonita-license.lic
              path: bonita-license.lic
