apiVersion: v1
kind: Secret
metadata:
  name: bonita-test-creds
stringData:
  DB_PASS: myDbSecret
  BIZ_DB_PASS: myBdmSecret
  BONITA_RUNTIME_ADMIN_USERNAME: admin
  BONITA_RUNTIME_ADMIN_PASSWORD: myAdminSecret
  MONITORING_USERNAME: monitoring
  MONITORING_PASSWORD: myMonitoringSecret
  #if monitoring creds changed, update also Basic Auth in bonita_deployment.yaml using the output of
  #echo -n "monitoring:myMonitoringSecret" | base64
  PLATFORM_LOGIN: pflogin
  PLATFORM_PASSWORD: myPfSecret
type: Opaque
