---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:15.7
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: POSTGRES_PASSWORD
              value: testpassword
      volumes:
        - name: initdb
          configMap:
            name: db-scripts
            items:
              - key: postgres_setup.sh
                path: init.sh
              - key: init-users-dbs.sh
                path: init-users-dbs.sh
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgresql-db
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
