apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bonita.fullname" . }}-hazelcast
  labels:
    {{- include "bonita.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
