{{- if and .Values.uib.enabled .Values.uib.builder.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bonita.fullname" . }}-ui-builder
  labels:
    {{- include "bonita.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.uib.builder.service.type }}
  ports:
    - port: {{ .Values.uib.builder.service.port }}
      targetPort: 80
      protocol: TCP
      name: bonita
  selector:
    {{- include "bonita.selectorLabels" . | nindent 4 }}
    app: uib
{{- end }}
