apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bonita-custom.fullname" . }}-setup-env-vars
  labels:
    {{- include "bonita-custom.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  DB_VENDOR: {{ .Values.bonita.datasources.bonita.vendor | b64enc | quote }}
  DB_HOST: {{ .Values.bonita.datasources.bonita.host | b64enc | quote }}
  DB_PORT: {{ .Values.bonita.datasources.bonita.port | b64enc | quote }}
  DB_USER: {{ .Values.bonita.datasources.bonita.username | b64enc | quote }}
  DB_PASS: {{ .Values.bonita.datasources.bonita.password | b64enc | quote }}
  DB_NAME: {{ .Values.bonita.datasources.bonita.name | b64enc | quote }}
  BIZ_DB_USER: {{ .Values.bonita.datasources.bdm.username | b64enc | quote }}
  BIZ_DB_NAME: {{ .Values.bonita.datasources.bdm.name | b64enc | quote }}
  BIZ_DB_PASS: {{ .Values.bonita.datasources.bdm.password | b64enc | quote }}
  BONITA_RUNTIME_ADMIN_USERNAME: {{ .Values.bonita.credentials.tenant.username | b64enc | quote }}
  BONITA_RUNTIME_ADMIN_PASSWORD: {{ .Values.bonita.credentials.tenant.password | b64enc | quote }}
  PLATFORM_LOGIN: {{ .Values.bonita.credentials.platform.username | b64enc | quote }}
  PLATFORM_PASSWORD: {{ .Values.bonita.credentials.platform.password | b64enc | quote }}
